name: Test with GHC and Cabal
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: "9.4.7"
        cabal-version: "3.10.1.0"
    - run: cabal build
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: "9.4.7"
        cabal-version: "3.10.1.0"
    - run: cabal test
